# Generated by Django 5.1.7 on 2025-03-18 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdb',
            name='pimage',
        ),
        migrations.AddField(
            model_name='patientdb',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientdb',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdb',
            name='model_type',
            field=models.CharField(choices=[('InceptionV3', 'InceptionV3'), ('MobileNet', 'MobileNet'), ('DenseNet', 'DenseNet')], default='InceptionV3', max_length=20),
        ),
    ]
